language: c

compiler:
  - clang
  - gcc

env:
  - LUAVER=5.1
  - LUAVER=5.2

script:
  - cd lua-$LUAVER/src && make linux CC=$CC && cd ../../luadec && make CC=$CC LUAVER=$LUAVER
  - make luareplace CC=$CC LUAVER=$LUAVER
  - make luaopswap CC=$CC LUAVER=$LUAVER
